---
driver:
  name: docker
  driver_config:
    binary: docker.io
    privileged: true
    remove_images: true

provisioner:
  name: chef_zero
  product_name: chef
  product_version: latest
  install_strategy: always

platforms:
  - name: centos-6.10
    driver_config:
      image: centos:6.10

suites:
  - name: default
    run_list:
      - recipe[hostfile::default]
    attributes:
      hostfile:
        host_entry: ['host1 1.1.1.1', 'host2 2.2.2.2']